workspace = '~/workspace'
shell = [
    '/usr/bin/zsh',
    '-c',
]
github_token = 'onhrefhprqrfovgrf'

[gitlab]
token = 'onhrefhprqrfovgrf'
host = 'gitlab.com'

# Example:
# workspace = '~/workspace'
# shell = [
#     '/usr/bin/zsh',
#     '-c',
# ]
# default_after_workon = 'echo default after workon'
# default_after_clone = 'echo default after clone'
# github_token = 'githubtokensecret'
# [gitlab]
# token = 'token'
# host = 'localhost'
